---
version: "3.6"

services:
  my-ssh-share:
    command:
      - "/bin/sh"
      - "-c"
      - "/start.sh"
    container_name: "my-ssh-share"
    hostname: "my_ssh_share_D6F9FCA6-0FF3-42F5-AE1F-F47595B768B0"
    image: "ssh:latest"
    ports:
      - "22222:22/tcp"
    restart: "unless-stopped"
    volumes:
      - "/srv/shares/a-shared-directory:/a-shared-directory"
